### ISSUE TITLE
Define codes for "level of assurance" 

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#1]
In our current implementations we use:

```
 [{
  "url": "https://github.com/TransparentHealth/800-63-3-trustmark#P",
  "valueCode": "P2"
  }],
```
e.g. to represent NIST 800-63-3 identity assurance level 2. This follows https://github.com/TransparentHealth/800-63-3-trustmark#nist-sp-800-63-3-digital-identity-guidelines-trustmark but we should formalize and perhaps define our own extension URL.

Right now we provide a single assurance level for the entire patient record; in future we might conceivably want element-level assurances.

**Comment by masnick** [comment]
@jmandel just to make sure I understand this correctly, you're proposing adding an extension to the Immunization resource to identify assurance level? We can definitely do this -- just want to make sure that we're doing the right thing 😄

**Comment by jmandel** [comment]
thanks for checking that I call him I was referring to an extension on the Patient resource where the demographics are captured. For example, [here](https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/0bd8f6de90d3917e91b73d063cf200dca426cc15/src/fixtures/vc-covid-immunization.json#L26).

**Comment by masnick** [comment]
Ah ok, sure, that makes sense.

**Comment by nkarip** [comment]
It looks like there is WIP that uses meta.security tags for this, based on v3 standards. http://build.fhir.org/ig/HL7/fhir-security-label-ds4p (I think in the May2021 ballot?). The terminology is different but it seems like https://terminology.hl7.org/2.0.0/CodeSystem-v3-ObservationValue.html#v3-ObservationValue-LOAID corresponds to P. So your example above would look like the below. Does that seem sufficient?

>   "meta" : {
    "security" : [{
        "system" : "http://terminology.hl7.org/CodeSystem/v3-ObservationValue",
        "code" : "LOAID2"
}]

**Comment by jmandel** [comment]
Cool! From http://terminology.hl7.org/CodeSystem/v3-ObservationValue it looks like this is a published code active as of 2019-03-20, but the value set isn't one currently recommend for use in security labels, and it seems weird that it's listed as an "ObservationValue" code system. Let me ping John Moehrke for a gloss on this.

**Comment by jmandel** [comment]
It doesn't seem like there's any "pat" advice on this. I'm not sure whether IAL counts as "specific security metadata" per the [intended scope of security labels](http://hl7.org/fhir/security-labels.html#6.1.1), and I can't figure out why http://terminology.hl7.org/CodeSystem/v3-ObservationValue has a set of codes about NIST 800-63 concepts.

My preference at this stage is to define an extension in this IG with a valueCode of `"P1" | "P2" | "P3"` in order to move forward, and revisit if better advice comes along.

**Comment by nkarip** [comment]
So it seems the IG tooling does not allow the format you put in the original comment - the URL of the extension has to match the location of the structure definition, and code systems cannot have the pound sign in them. So I can make it look like this

> "extension" : [
    {
      "url" : "http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-level-of-assurance",
      "valueCode" : "P1"
    }
  ]

or like this

> "extension" : [
    {
      "url" : "http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-level-of-assurance",
      "valueCodeableConcept" : {
        "coding" : [
          {
            "system" : "https://github.com/TransparentHealth/800-63-3-trustmark",
            "code" : "P1"
          }
        ]
      }
    }
  ]

**Comment by nkarip** [comment]
The "Integrity Category" of security labels described at http://hl7.org/fhir/security-labels.html#hcs seems to indicate this might be in scope for meta.security. Since there is no required binding for code, we could use the trustmark values instead of ObservationValue.

**Comment by jmandel** [comment]
`http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-level-of-assurance` is super long. If we go this route, maybe `http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/ial` would help a bit. 

Or it'd even be valid to have a profile with an invariant to ensure that one of three codes `IAL1`, `IAL2`, `IAL3` (irrespective of "system") was present on the instance, like:

```
{
  "resourceType": "Patient",
  "meta": {
    "security": [{ "code": "IAL1" }]
  }
}
```

**Comment by Mturman3** [comment]
Does the combination of proposals above require the Issuer to make an assertion about how the data in the patient resource was collected?

**Comment by juliemaas** [comment]
Are you referring just to the most recent definitions I made or to the broader context of level of assurance here? It's my opinion that IAL1 (just above and as in 800-63-3a) is somewhat of a pass-through "this is the info as we collected from the patient, specifically name and dob as in this Health Card". Would you suggest adjusting the definition or the code name itself in some way?

**Comment by Mturman3** [comment]
As an Issuer, IAL1 is likely the only claim we can make on the origin/veracity of the data. Any further assurance would fall to the SoPs of a given healthcare provider.

**Comment by juliemaas** [comment]
The related policy might indicate that it's the provider who is asserting that identity assurance (i.e. standing behind it). Or is the Issuer generally standing behind all data within the Health Card?

**Comment by jmandel** [comment]
Agreed that policy should address this -- I think the desired outcome is for the immunization provider to make a representation of what level of identity assurance they achieved.

**Comment by Mturman3** [comment]
'immunization provider' being the key for me - as an Issuer, am I to make that representation on their behalf? I don't have any way of knowing that today.

**Comment by jmandel** [comment]
Agreed, this could be a use case for multiple patients, (or perhaps something like using these LOA tags on Immunization for the case where tags on Patient can't tell the full story).

**Comment by JohnMoehrke** [comment]
I would expect two different vectors to be recorded. One would be an overall LOA level achieved. The other would be the method used to achieve that level. In this way a relying-party can make an informed decision. In this way a previously evaluated method can be dynamically elevated or lowered. The overall LOA is intended to be used as primary input to the relying-party, with the other vector being available as backup.

**Comment by juliemaas** [comment]
Apologies if I am missing context from earlier conversations about outside doses...but that has been on my mind too. It may inform our discussion to put some more details into that 2-provider use case mentioned above; for example: 

-LOA tag on Patient is IAL1.4 due to policies at vaccine scheduling being sufficient to associate immunizations with the record of a patient whose name and date of birth were verified using a state issued photo ID or nationally issued photo ID (for example, the scheduling system matches on name, date of birth, & SSN, so this Patient is tagged with the highest assurance we are currently able to express through name and date of birth alone, IAL1.4)

-1st dose was administered by provider #1 and includes an IAL1.2 tag on Immunization because that provider's vaccination check-in process requires ID but allows a variety of ID types at the site where it was administered (we can't get all the way to the record's LOA of 1.4)

-2nd dose, self-reported by the patient as being administered by provider #2, does not have an LOA tag on Immunization as there is no provider to assert it (if a code is required on Immunization, an "Unknown" code may be needed)
 
The idea being to clearly distinguish between the outside dose case and "self-asserted" patient identity, and for encounter-level assurance to reflect these differences when needed.

**Comment by JohnMoehrke** [comment]
This is moving away from IAL, and moving more toward AAL.   I really think we need to focus on one or the other. We either are addressing the strength of identity provisioning (IAL), or we are expressing the strength of authenticating the patient at the time of an activity (AAL).   I am good with us deciding we need both, but I really think that the urgency is IAL of the  Patient identity provisioning.

**Comment by juliemaas** [comment]
Interesting. I see three different identity verification events being conveyed in the use case, leaving authentication out of scope (except that the IAL of certain aspects of the record may be different, depending on what AAL is used to associate an immunization with a higher-assurance record). For example, some might feel the "1st dose" example above is the same identity LOA as the record if the patient authenticated to an IAL2/AAL2 portal account to make the appointment and some form of ID is used to check-in at the site. Interested to hear feedback from others.

**Comment by jmandel** [comment]
I still think what we want is "just" a way to answer the question "Did an immunization provider take steps to verify a patient's name and birthdate, or were these self-asserted?"

We're at risk of drowning in complexity to the point of making this unworkable if we try to parse out exactly what steps, or the connections between these steps and prior/subsequent patient authentication events, etc.

If we define a simple "yes we checked" extension, we might find that few providers are willing to assert this. But at least we'll have a framework and can use that as a starting point for future work.

**Comment by juliemaas** [comment]
OK Josh. I was pushing the boundaries a little, to test the definitions just in case they don't make sense. Let's see how it gets picked up?

**Comment by jmandel** [comment]
Looking through implications above, an issuer might receive records about an individual patient from >1 information sources (i.e., immunization provider) -- call them "Source A" an "Source B".

JCM Suggestion 1: If patient name and DOB from Source A don't match those from Source B, and the issuer can't resolve the differences, then the issuer should issue two health cards (one with the immunization and demographics from Source A, one with the immunization and demographics from Source B).

If patient name and DOB match but Source A can attest to having verified these ID attributes and Source B cannot attest to having verified them... this leaves an open question.

JCM Suggestion 2: We should move the "IAL attestation" extension (or security label) from Patient to Immunization, interpreting it as "This immunization was performed in the context of Identity Assurance Level 1.2" (or what-have-you).

**Comment by JohnMoehrke** [comment]
I still think that the whole reason we are doing this is to enable the Relying-Party to have some faith that the immunization credential is for the human THEY have in front of them. Thus they need to know to what level they can trust the Patient identity details. Our Relying-Party is not worried about the Patient Safety issues that healthcare tends to put highest. They are worrying about the safety of the community they are about to allow the Patient to interact with (the plane load of people). Further the most likely varrability is on identity proofing of the Patient, less likely that each immunization activity is going to happen in different levels of assurance.

That said, it seems like the discussion continues to have a thread about the assurance of the act of immunization. And there seems to be discussion in here about what was checked and who checked it... That seems more like an Observation. If we really think that this information is needed, at this level of detail, then define an Observation. or define a Provenance.  

I really don't think that the Relying-Party down stream cares about this information. That is not to say it isn't important, I am more focusing on what are they needing. I think if we provided it, no one would look at it.

**Comment by jmandel** [comment]
> I think if we provided it, no one would look at it

This is indeed a risk, which is why I would like to provide the simplest most straightforward flag we can, and move on. That said, the ability to convey identity binding information has been a core requirement from the beginning, so I don't think we can skip it all together. Providing something small will help us learn what the market needs.

**Comment by JohnMoehrke** [comment]
I think (Required) Patient.meta.security holding a value similar to IAL (new codes we invent for IAL 1.5 and such). These are statements of the quality of identity assurance used to provision the identity (IAL). Policy statements, like NIST 800-63 defines. Shall be ONE of the codes from a defined valueset. 

Second level that might be nice to have (Optional) would be to add to Patient.meta.security some code indicating the method used to get to that IAL. Based on some IG defined codes (checked Real-ID qualifying picture id, etc..) With extensible binding.

done

**Comment by juliemaas** [comment]
Yes I think we have both these levels explicitly in our definitions. What I realized in the use is that we probably also need an Unknown code, for outside doses that I receive somewhere else and self-report to my provider, if the code is to be required.

**Comment by nkarip** [comment]
Based on this discussion and the focus on level of verification at time of vaccine administration, have modified PR to assert IAL on immunization.meta.security. This is a solution-for-now rather than a solution-forever and needs a larger discussion with the FHIR community regarding LOA outside the context of the vaccination IG.
