### ISSUE TITLE
What is the specific value of `primarySource`?

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#11]
Making this element required surprises me a bit. I'm not sure exactly how it'll be interpreted, and forcing people to populate `false` if they aren't sure just adds an extra property to the instances. In general, I don't expect a record to be unreliable when this is `false`, and the "real story" is probably hard to tell with just a boolean. I'd lean toward omitting.

**Comment by nathanbunker** [comment]
My comment is that from Immunization Information Systems (IIS) they always record this information. However, there has been a lot of discussion about reporting this primarySource information out of the IIS. 

The issue at hand is that this field was originally created to signal to the IIS that the reporting system is the primary source of this digital information and has first hand information. This flags the IIS to decrement inventory and/or assign the medical home for this patient. It also allows for placing greater confidence in the data reported as "administered" in preference to matching data being sent in as historical from other submitters.

Having said all this, the meaning of the field becomes difficult when the IIS reports this out to other systems. If the immunization was reported as administered by a submitter is it then considered a primary source immunization if it's reported by the IIS to other IIS? The general consensus seems to be that all immunizations in the IIS should be reported as NOT primary source, unless the IIS was acting as the primary system for recording the vaccinations (i.e. it is the source of the medical record) Which is a scenario that is rare.

So the question is, does the primarySource concept transfer from system-to-system, or does it essentially disappear once it moves from one electronic system to another?

**Comment by nathanbunker** [comment]
Another comment is that for IIS-to-IIS communication, IIS are not interested in whether the immunization was reported as primarySource or not. The receiving IIS normally records all immunizations given by an IIS as NOT primarySource, without regard to what the originating IIS represents the information.

I'm not sure how useful this information will be for a verifiable credential. IIS are working at the point of only reporting immunizations that they are confident are verified on the record. So I'm not sure what the value is to communicate this primarySource going forward. In fact, if it was required, for IIS I would recommend to always indicate this as NOT primarySource.

**Comment by arztnh** [comment]
I think Nathan has this spot on. But there is a larger issue of how "authoritative" IIS data is in the first place given than it all comes from somewhere else. A skeptic might question it's authenticity, but on the other hand there are existing legal processes (like school compliance) that rely on IIS as official records (in TN the record from the IIS is the ONLY acceptable record). One important realization is that the data from ANY system are really only accurate at the moment you query, right? Anything is subject to correction/redaction later.

**Comment by Mturman3** [comment]
An EHR could produce Immunization records that are both primarysource='true' (administration recorded in EHR) and primarysource='false' (immunization recorded historically) for the same patient, possibly within a single VC. Is one of these records weighted differently than the other by a Verifier? That will add an additional layer of complexity to all parties, I think.

**Comment by arztnh** [comment]
There is no single answer to that, right? _Some_ parties may interpret the statuses differently, some may not. That's why the standard allows one to specify.

**Comment by nathanbunker** [comment]
The use case where a single system sends both primary and non-primary is not a useful case. What would be expected of the receiver to differentiate these two types of information? If we want these to be interpreted differently then we will really want to define exactly what is considered "primary source" and what is not.

However I could see a use case where the signer/affirmer of the information might be either an IIS or the organization that oversaw the administration.  Perhaps the verifier would find that information useful? But that would be meta information, either in the information about the signer/affirmer, or something that is known about them from a registry?

**Comment by masnick** [comment]
`primarySource` is set to `1..1` in [US Core's Immunization profile](http://hl7.org/fhir/us/core/STU3.1.1/StructureDefinition-us-core-immunization.html), which we inherit from.

Given the discussion above and the space constraints in the VC, I don't think it make sense to have this element required. This would mean directly profiling the base Immunization resource rather than inheriting from the US Core version.

@jmandel and others, is using US Core important for a specific reason, or are we ok deviating from it?

**Comment by jmandel** [comment]
I think we're using US Core as a starting point to ensure we're incorporating the basic design. We're free to disagree with specifics, and in this case that'll have the technical impact of not being able to "inherit" (in a FHIR "base profile" sense) from US core, even though we'll still *use* most of the constraints. We've already done a similar thing with US Core Patient, so it seems like a fine decision here too.

**Comment by masnick** [comment]
We need to move from US Core's Immunization profile to the base Immunization resource in order to do #17.
