### ISSUE TITLE
vc-lab-1 constraint missing expression?

### ISSUE THREAD

**Issue by prb112** [dvci/vaccine-credential-ig#111]
Not sure the right venue to ask/open an issue with one of the Constraints in the structure definition from the package in the release to http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/package.tgz 

The structure definitions include vc-lab-1 which does not have an expression. 

```
"resourceType": "StructureDefinition",
	"id": "covid19-laboratory-bundle",
```

```
{
 "key": "vc-lab-1",
				"severity": "error",
				"human": "Bundle SHOULD only include results with status final or status that is subsequent to final.",
				"source": "http://hl7.org/fhir/uv/smarthealthcards-vaccination/StructureDefinition/covid19-laboratory-bundle"
			}
```

Should this constraint https://github.com/dvci/vaccine-credential-ig/blob/main/input/fsh/invariants.fsh#L2 include an expression such as `Expression: "status.exists()"`?

Apologies if there is a better venue.

**Comment by nkarip** [comment]
Thanks for pointing this out. There is a new invariant in dev that will be pushed to main in the next release that explicitly checks an Observation resource status "observation-status-shall-be-complete". We also wanted an indicator at the Bundle level that states that the Bundle should only include Observation entries that are finalized and this seemed like the best way to display this in the IG. We'll check on whether there is a expression that can enforce this.

**Comment by prb112** [comment]
Thank you
