### ISSUE TITLE
When using the "other please specify" pattern, suggest additional Codings

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#12]
In the documentation and examples for "other, please specify" -- like:

```
  "vaccineCode" : {
    "coding" : [
      {
        "code" : "OtherVaccine",
        "display" : "Other vaccine without published CVX"
      }
    ],
    "text" : "Acme, Inc. COVID-19 vaccine (EUA)"
  },
```

- [ ] I think the example is missing a `system` (of "http://hl7.org/fhir/us/vaccinecredential/CodeSystem/vaccine-credential-other-code-cs"?)
- [ ] I'd consider showing an additional Coding in the array, to show it's okay to use non-standard codes when `OtherVaccine` is present.

**Comment by masnick** [comment]
This is fixed in `main`.
