### ISSUE TITLE
Add valueString support to lab results

### ISSUE THREAD

**Issue by masnick** [dvci/vaccine-credential-ig#134]
This is needed because many lab results are not quantitative or associated with a code.

This will include a very stern warning to not use valueString unless absolutely necessary, and that Verifiers are unlikely to be able to decode the contents of valueString if Issuers cannot.

Will also include a note that valueString may be deprecated or disallowed in future versions of the IG, and that Issuers should begin working with the laboratories to start getting SNOMED or similar codes attached to results to prepare for this.

valueString will also have a length invariant attached.

**Comment by nkarip** [comment]
Might want to relax reference range invariant to allow it for valueString in addition to Quantity. Might be helpful for verifiers to figure out the meaning of the string result to have a "normal" value provided in range.

**Comment by masnick** [comment]
Fixed in dev
