### ISSUE TITLE
Add example showing bundle wrapped in VC

### ISSUE THREAD

**Issue by masnick** [dvci/vaccine-credential-ig#14]
This will be helpful in showing how the FHIR IG should be used in practice. This also gives us an opportunity to have an example without the extra fields SUSHI adds in (see #5 and #6).

/cc @jmandel

**Comment by masnick** [comment]
Make sure that this includes the target disease per #2, and add prose documentation explaining that the VC wrapper is the correct place to indicate target disease.

**Comment by nkarip** [comment]
Do we still want to do this with the HL7 Public Health workgroup request to separate the IG from the Health Cards spec?

**Comment by masnick** [comment]
Let's just link to https://smarthealth.cards/examples/ which has some examples that include the FHIR bundle.

We should also make sure those examples pass validation once we merge the DM profile branch in. I'll log an issue for that.
