### ISSUE TITLE
vc-shall-not-be-a-covid-loinc in infectious-disease-laboratory-result-observation fails validation

### ISSUE THREAD

**Issue by nkarip** [dvci/vaccine-credential-ig#142]
FHIR Validator throws error for invariant vc-shall-not-be-a-covid-loinc validating infectious-disease-laboratory-result-observation profile for all LOINC codes, including those not in COVID value set.

Validating a COVID lab with profile covid19-laboratory-result-observation shows the warning "ValueSet http://cts.nlm.nih.gov/fhir/ValueSet/2.16.840.1.113762.1.4.1114.9 not found by validator", which may be the root of invariant error.

**Comment by nkarip** [comment]
Turns out invariant needs to use code.coding instead of just code in memberOf function.

**Comment by masnick** [comment]
Merged PR
