### ISSUE TITLE
How to link to Locations

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#15]
We haven't established good guidance about linking to the facility (location) where an immunization was given. Do we want to provide this? Should it be just text or a full resource (in which case, what fields should be populated?)

**Comment by masnick** [comment]
The [US Core Location profile is specified as a slice in the bundle](https://github.com/dvci/vaccine-credential-ig/blob/main/input/fsh/profiles.fsh#L165). Looking [at the profle](https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-location.html), there are some MS that are probably not necessary for our use case.

@jmandel what about instead profiling [Location](http://hl7.org/fhir/R4/location.html) with the following:

```text
* name 1..1 MS
* address MS
```

We could also include `* telecom MS` if it's important for some actor to be able to contact the location.

**Comment by jmandel** [comment]
I like this idea, though it's possible we can get by with just `reference.display` and not actually including a `Location` resource at all.

**Comment by nkarip** [comment]
There are 2 spots where USCoreLocation is used - entry in the VaccineCredentialBundle, where I don't think it's possible to use reference.display, or on VaccineCredentialImmunization. Are we talking about using a profile for both instances, or just in VaccineCredentialImmunization? I might prefer the suggestion from @jmandel if it's the later, using reference.display and keep USCoreLocation for the bundle. Seems simpler, though I don't know how you would structure it in the IG in a way that could be programmatically validated in a data minimization profile. Profile the Reference resource?

**Comment by jmandel** [comment]
We don't have good guidance about what kind of location details we actually need to convey. If we can get this down to just "Populate `.location.display` in the Immunization resource, and no need to add a Location to the Bundle", that'd be ideal IMHO. If we *do* want separate Location resources, we need guidance about why and what belongs in them (the US Core Location must-support list is definitely more detail than we'd want issuers to put in a health card).

**Comment by masnick** [comment]
I think it's worth including a stripped down profile for Location. We might be able to get away with `location.display`, or verifiers (or patients) may decide they need more information down the road.

We can use the `location.display` approach in the data minimization profiles and see if anyone objects.

**Comment by Mturman3** [comment]
Location is a complex entity in an EHR. K=Locations (plural) exist in relation to an Immunization, from Nurse Unit to Organization. Which location.display is most valuable to the Holder/Verifier?

**Comment by jmandel** [comment]
I agree with @Mturman3's point. I think a simpler recommendation would be to populate `Immunization.performer.actor.display` with the name of an organization or a person -- maps to the rightmost column on a CDC vaccination card like:


![image](https://user-images.githubusercontent.com/313089/109081221-8d87f880-76c7-11eb-9893-2ba4b0cee405.png)

I don't think this needs to be super structured/interoperable, but helps map to existing practices and provides some starting point if you want to track down further details.

**Comment by Mturman3** [comment]
To be clear, Cerner's resource is going to return two different things between performer.actor and location.managingOrganization.

Actor will be the more granular individual and managingOrg a (somewhat) recognizable health system/organization name.

My recommendation is to provide managingOrg.display in the VC payload if a Location is desired by consumers/Verifiers.

**Comment by masnick** [comment]
@Mturman3 got it, thanks!

**Comment by jmandel** [comment]
`performer.actor` is a "Reference(Practitioner | PractitionerRole | Organization)" in FHIR -- so it can be the name of an individual or an organization. That matches the CDC card "righthand column" semantics -- and if we want we can populate "type" on the reference to explain whether it's a person or an org -- e.g.

```
"perforomer": [{
  "actor": {
    "display": "Dr. Jones",
}}]

"perforomer": [{
  "actor": {
    "display": "ABC General Hospital",
}}]

"perforomer": [{
  "actor": {
    "display": "Dr. Jones",
    "type": "Practitioner"
}}]

"perforomer": [{
  "actor": {
    "display": "ABC General Hospital",
    "type": "Organization"
}}]


```

**Comment by masnick** [comment]
@Mturman3 It looks like `managingOrganization` only appears on Patient, and we need something that fits in Immunization. Does doing what Josh suggested (using `Immunization.performer.actor` constrained to `Organization`) work?

**Comment by jmandel** [comment]
(I think @Mturman3 was talking about http://hl7.org/fhir/location-definitions.html#Location.managingOrganization (so, linking from Immunization -> Location -> Organization). Semantically this is fine but I'm concerned that it adds more resources than we need to the bundle without a clear advantage.

**Comment by masnick** [comment]
> I think @Mturman3 was talking about http://hl7.org/fhir/location-definitions.html#Location.managingOrganization 

Got it, thanks for clarifying.

----

Thinking about this from a use case perspective, I want to make sure we're providing verifiers with useful information here if we're paying the payload size cost of even `performer.actor.display`. 

For example, we could end up with something really generic like `University Hospital` or `Acme Pharmacy` that's not really meaningful. We can ask for `University Hospital, New York` but that then becomes a parsing mess for verifiers when they also get `University Hospital, NYC` and `University Hospital of New York`.

Having the street address to cross reference would potentially be beneficial for verifiers, but that adds a lot of size to the payload and issues may not even have the data for it.

(We will also need to limit the length of `performer.actor.display` with an invariant. We should do this for all other strings too -- they can be up to 1MB per FHIR spec. Added #51.)

@jmandel do you have a sense of whether a string in `performer.actor.display` fulfills the verifier's needs?

**Comment by jmandel** [comment]
Honestly I think the value in populating this information is simply to achieve parity with what is available in the CDC paper card. This way we can give you a CDC paper card and we can give you a QR with the same information (and of course more structure and computability where it makes sense -- I'm just arguing that this particular field is one where it probably doesn't make sense).

**Comment by masnick** [comment]
That seems reasonable. I will incorporate into the IG.

**Comment by nkarip** [comment]
Linked PR removed Location from profiled bundles and provides guidance and restrictions around performer for immunization profile. I applied the same guidance to lab performer, since there is a similar use case there. Also disallowed Location reference in the data minimization profiles. Submitted PR to dm-profiles branch rather than main. @masnick, I assigned you for review.

**Comment by nkarip** [comment]
From @Mturman3 at https://github.com/dvci/vaccine-credential-ig/pull/53#issuecomment-789742706
> My general concern with this approach is that it creates drift between our R4 Immunization resource when requested directly vs the representation in the VC.
> 
> In complicates the implementation and puts us in a position that the generation of each CredentialType cannot be generalized across resources, but must be a one-off set of rules/logic to process each resource for a given Health Card Profile.
> 
> Additionally, this is the only (?) element in the bundle purely intended for human consumption - are the above considerations outweighed by the perceived value that a 'Location' provides the Holder/Verifier?

Perhaps we should bring it up with a larger group? I think in general each credential type will require processing to fit a health card profile, that is the nature of profiles. And while Organization name is not computable, the reference could additionally provide a URI/URL that could be computable if there is a use case. The same is not true of a Location. But we can take it to a larger audience.

**Comment by Mturman3** [comment]
The approached proposed in the PR achieves the goals of this profile (data minimization, self-contained, and real-world parity).

My concerns are raised as an implementer tasked with assembling/forming the VC and to highlight where these decisions create additional complexity both in the short/long-term for implementers of these standards.

As we gain more experience with this specification, we can revisit how Organization/Provider/Location should manifest in the VC.

**Comment by masnick** [comment]
We are using the `performer.actor.display` approach for immunizations, and `performer.display` for lab test results. This is merged into `main`.
