### ISSUE TITLE
Remove inherited vaccineCode example binding from Immunization profiles

### ISSUE THREAD

**Issue by nkarip** [dvci/vaccine-credential-ig#159]
Immunization profiles (AD and DM) show example binding VaccineAdministeredValueSet for vaccineCode inherited from core Immunization in snapshot table.

**Comment by masnick** [comment]
[Example bindings can't be removed](https://chat.fhir.org/#narrow/stream/179166-implementers/topic/IG/near/234918476), but I was able to replace with an example binding for CVX, which makes more sense.
