### ISSUE TITLE
Data minimization: discouraging use of certain elements

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#16]
We want to discourage use of unnecessary elements, from a data minimization perspective. We might want to prohibit these through cardinality restrictions, but I'd suggest it's better to just use a flag (or notes) to mark them as discouraged. We may also want to discourage, in a blanket statement, the use of any elements that aren't explicitly flagged as "must-support" (and then apply that flag to to the recommended elements).

**Comment by Mturman3** [comment]
How are Verifiers meant to interpret the 'must-support' elements of the profile? Will those elements be assumed to be fair game in verification rules? The case where an Issuer is not able to value all 'must-support' fields (e.g. PrimarySource='false') could cause the credential to fail verification.

**Comment by masnick** [comment]
In the IG I believe we should state something like:

> Issuers SHALL populate any elements marked as MustSupport if the necessary data are available in their system. Due to the payload size constraints for the VC use case, Issuers SHOULD NOT populate any elements that are not marked MS unless they contain valuable information for verifying the vaccination.

I don't think the MustSupport flags should be considered meaningful for the Verifier beyond identifying elements they can expect to see in the VC. More generally, I don't think guidance on what constitutes a valid VC is within the scope of this IG...this seems like something that is really up to the Verifier.

**Comment by jmandel** [comment]
Agreed with the edit in Max's last comment. The idea is it's not okay for verifiers to unintentionally ignore these elements. They can decide for themselves whether the elements are in fact relevant to the conclusions they draw.

**Comment by Mturman3** [comment]
I understand that the the designation of MustSupport is primarily to communicate to Issuer implementers. I also understand that the intention of this spec is not to define what a Verifier should validate within the VC - but we are making a determination that certain elements are more important than others because of their potential value to Verifiers. If those elements are not populated in 30+% of issued VCs - a Verifier cannot reliably use that element to validate the VC and therefore it loses its value.

**Comment by masnick** [comment]
@Mturman3 I'm going to open a separate issue about making sure that we have `MS` on key fields from the Verifier's perspective.
