### ISSUE TITLE
Please revert disallowing Patient.identifier in the AD profile

### ISSUE THREAD

**Issue by igorsirkovich** [dvci/vaccine-credential-ig#164]
Please revert https://github.com/dvci/vaccine-credential-ig/issues/98 and let implementers decide whether to allow Patient.identifier in the AD profile. Otherwise, many jurisdictions (e.g. Canadian provinces) will have to give up on the Health Cards conformance due to their legislative and business requirements around patient identification. If necessary, please provide additional guidance, e.g. discourage leaking MRN numbers, but please avoid making this unusable by other (non-US) jurisdictions.

**Comment by masnick** [comment]
@igorsirkovich Thanks for reporting this. We understand the need and are looking at how to support `identifier`.

**Comment by nkarip** [comment]
Please also see #161 where a thread has been started related to this.

**Comment by igorsirkovich** [comment]
> Please also see #161 where a thread has been started related to this.

Thank you Neelima! I had missed this.

**Comment by masnick** [comment]
@igorsirkovich this is addressed in a branch: http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/reorganize/profiles.html

It's still under development, but there is now a profile of Patient that allows `identifier`: http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/reorganize/StructureDefinition-shc-patient-general-dm.html

I expect this to be merged in within the next week barring major issues identified when we ask for feedback from the community, but in the meantime feel free to validate against the profiles on this branch.

**Comment by igorsirkovich** [comment]
Thank you @masnick!

**Comment by masnick** [comment]
Closing since this is getting merged in shortly.
