### ISSUE TITLE
Issue moved and reposted: Source of truth for immunization records?

### ISSUE THREAD

**Issue by arztnh** [dvci/vaccine-credential-ig#19]
My original post mistakenly put in the health-cards issue list:

"I am not sure if this is in scope for this project, but the notion of "source of truth" for immunization records is an open issue. Is it the EHR? IIS? Both? Either? Note that for both the EHR and IIS that records can change and be corrected for many reasons: simple errors, discovery of a bad vaccine lot invalidating the efficacy of the dose administered. Should the patient be able to capture their immunization record and store it in their digital wallet and assume it is forever "true"? Should they be made to validate that record from its source?

A secondary issue involves IIS or other points of record consolidation (potentially an HIE). They are only as good as the systems that submit data to them (primarily EHRs) but also apply some quality assurance steps to consolidate a coherent record for a patient. Should they be a preferred, more centralized source of information over an EHR?

Does this project even care about these distinctions?"

**Comment by arztnh** [comment]
Josh Mandel responded in the other issue list before closing the issue:

"Thanks @arztnh for these questions. The quick answer is it'd be great if you can raise this issue in the "COVID-19 Data Profile IG" at https://github.com/dvci/vaccine-credential-ig/issues (GitHub won't allow me to move the issue directly).

Thinking from the Covid-19 data profile perspective, we want to allow for some flexibility in modeling these details:

- Issuers are in charge of deciding whether and when to expire a credential, by optionally setting an exp value. We recommend against this in general, but in some circumstances this may be prudent. A verifying party can check to see whether a credential is past its expiration date when validating the credential.

- Regarding sources of truth, we use the FHIR https://hl7.org/fhir/R4/immunization-definitions.html#Immunization.primarySource flag to indicate whether information has been recorded from a primary source. Again, this information is captured in a credential but it's up to a verifier (or: the algorithm a verifier chooses to apply) to decide whether to "discount" its trust in data based on this flag.

So: this project very much cares about the distinctions you raise, and we want to make sure they can be communicated clearly. But we don't set the rules on how much they matter to verifiers,

**Comment by arztnh** [comment]
The question is beyond the issue of primary source. It has more to do with the fluidity of the data itself. But I suppose this is endemic to health data in general. My point was more than an immunization from a primary source viewed _today_ may not still be a valid immunization (or even still in the patient's record) _tomorrow_.

**Comment by masnick** [comment]
@arztnh do you think the IG should be changed to take this into account? It seems like it might fit as part of the content on [`index.md`](https://github.com/dvci/vaccine-credential-ig/blob/main/input/pagecontent/index.md) -- we would definitely appreciate a PR if you have something specific in mind.

**Comment by Mturman3** [comment]
The VC represents a health fact at a point in time, regardless of which system issues it. We are already seeing rules from Verifiers regarding the recency of a health fact, e.g. 'negative'  lab within 72 hrs of flight. This example is not perfectly analogous to a vaccine credential, it does show that Verifiers can and do check the age of the health fact. The issueanceDate field in the VC wrapper would allow for the same kind of check to occur. Given the current state of the vaccine rollout and questions about new strains, I don't think this group has the information to make a determination on when/if a Health Card should no longer be valid based on when it was issued.

**Comment by nkarip** [comment]
I think it's beyond the scope of the IG, which deals primarily with data model, to determine when and how a vc should be invalidated. That might be better discussed on the zulip chat.

As far as data elements, as per @jmandel's earlier comment the https://hl7.org/fhir/R4/immunization-definitions.html#Immunization.primarySource element is meant to record whether the issuer was the originator of the record. Unless there is a particular concern around that, I will close this issue. If there is concern, then it would help to have a defined use case.
