### ISSUE TITLE
Leave explicit "targetDisease" modeling out of scope?

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#2]
My current thinking has been that things like target disease are best captured in the VC wrapper around these clinical data. We use the VC `type` fields for this, which allows some more natural negotiation about which credentials to request/share in a given use case.

Nothing prevents us from doing both, but this seems like a lot of overhead, and ultimately this kind of information should be derivable from the immunization products or lab test details.

**Comment by masnick** [comment]
Ah, I did not know this would be covered by the VC wrapper!

I wanted to make sure we had a way to capture this when an Immunization resource wasn't included in the bundle, but there's no good way to do this for `VaccineCredentialImmuneStatus` without using an extension.

**Comment by masnick** [comment]
targetDisease should not be MS or required; explaining how to specify target disease is covered by #14.

**Comment by masnick** [comment]
We resolved this as part of the switch away from US Core.
