### ISSUE TITLE
Naming to align with SMART Health Cards

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#20]
In this week's VCI call we discussed confusion in navigating between two specs. We thought consistent naming could help -- calling this: "SMART Health Cards: Vaccination IG"

So we'd have:

* SMART Health Cards Framework
* SMART Health Cards: Vaccination IG
* (later) others...

**Comment by masnick** [comment]
We will update the IG accordingly.

**Comment by masnick** [comment]
If we are adding lab values to the IG as described in #44, "SMART Health Cards: Vaccination IG" may be confusing.

I recommend we use "SMART Health Cards: Vaccination & Testing IG" instead, but welcome any suggestions others have.

**Comment by jmandel** [comment]
Makes sense to me
