### ISSUE TITLE
Examples seem to conflate Patient.contact and Patient.telecom

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#25]
Example Patients have `Patient.contact.telecom` populated with email and phone numbers -- but I think these examples should be showing data in `Patient.telecom` instaed of `Patient.contact.telecom` (since they are presumably details about the patient, rather than about a third party with some relation to the patient).

**Comment by jmandel** [comment]
e.g. https://github.com/dvci/vaccine-credential-ig/blob/main/input/fsh/examples_scenario1.fsh#L13-L17

**Comment by nkarip** [comment]
I think you're right based on the example email. @masnick correct me if this was not the intention.
