### ISSUE TITLE
Consider Verifiers' perspectives in MS and cardinality

### ISSUE THREAD

**Issue by masnick** [dvci/vaccine-credential-ig#32]
In drafting the initial version of the IG, I made some assumptions about which elements seem important for verification. I think it would be helpful to take a more systematic approach to this.

Ideally we should be adding `MS` to any elements that provide meaningful signal to verifiers.

Thinking in terms of Verifiers, I think we should avoid adding cardinality `1..` unless Verifiers can never verify the VC without the field. For example, `Patient.name` should presumably be `1..1`, but `Patient.birthDate` should not be `1..1` (in my experience this is often left off the paper vaccination cards even though there is a line for it).

I'm not sure if we have any Verifiers who are part of the Working Group. If we do, it would be great to get a sense of how they'll be thinking about verification criteria to make sure the `MS` flags are supporting their data needs as much as possible.

/cc @Mturman3 @jmandel re: #16

**Comment by jmandel** [comment]
Agree with the point that more input from verifiers.will be useful to validate decisions in the guide, but I'd be very cautious with `1..1` constraints especially on demographics. As we improve the API for generating credentials over time, I expect that we will see wallet applications able to request credentials with specific fields included or omitted depending on specific scenarios, and I would hate for us to rule those possibilities out here.

**Comment by masnick** [comment]
Completely agree on caution with `1..1` constraints.

Reece pointed me to https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf, which are EU guidelines on proof of vaccination. I haven't had time to read through this yet, but it may provide some information on the verifier's perspective.

**Comment by Mturman3** [comment]
I keep coming back to a criteria that MS 1... elements be meaningful to a verifier AND broadly supported by Issuers. Starting with a bare minimum and adding as real-world feedback comes in. 

We may have gotten pretty near to the above with the suggested changes to isSubpotent and protocolApplied elements. primarySource still has some valid questions to be settled.

**Comment by masnick** [comment]
Issuers and Verifiers have now had a chance to review the IG.
