### ISSUE TITLE
Data Minimization: Recommended Data

### ISSUE THREAD

**Issue by radamson** [dvci/vaccine-credential-ig#34]
Related to #16, but focused on the actual elements that are recommended to be included rather than how it should be indicated. Sharing the notes below from another meeting to help base updates and further discussion on:

----

### References
[CDC Vaccination Record Card (for reference)](https://health.wyo.gov/wp-content/uploads/2020/10/2020-COVID-19-shot-card-2b.pdf)

[Privacy](https://smarthealth.cards/#privacy)

### Design Goals
It is an explicit design goal to let the holder **only disclose a minimum amount of information to a verifier**. However, because the credential cannot be altered after it is signed, care must be taken in advance to select the appropriate information to include within the credential. While the information required to be disclosed will be use-case dependent, a single credential will also need to work in a variety of scenarios. Thus, a careful balance must be struck between the competing priorities of data minimization and general utility.

The granularity of information disclosure will be at the level of an entire credential (i.e., a user can select which credential to share from a Health Wallet, and each credential is shared wholesale).

A common definition of data minimization can be found in the GDPR Article 5(1)(c), which says:

> “1. Personal data shall be:
> (c) adequate, relevant, and limited to what is necessary in relation to the purposes for which they are processed (data minimisation)”

In order to satisfy these principles, the set of recommended data for a vaccine has been outlined below, including elements that should be included and elements that should not be included. Each included element should either be relevant for the downstream verification workflow or determined to be otherwise useful for the use case of credential presentation (such as information found on a standard vaccination card).

**<ins>VaccineCredentialPatient</ins>**
* Recommended for inclusion:
  * First name
  * Middle initial
  * Last name
  * Suffix
  * Gender
  * Mobile phone
  * Email address
  * Date of birth
  * National unique patient identifier, where available 
* Recommended for exclusion:
  * Non-government issued patient identification numbers such as a Medical Record Number
  * General government issued identifiers such as Social Security Number
  * Race or ethnicity
  * Marital status
  * (photo?)
  * Care team members
  * Address
* Additional guidance:
  * Parties responsible for collecting mobile phone numbers should attempt to verify the number upon collection (e.g., using an SMS with a confirmation link or one-time code)
  * Verifiers should not store identity data conveyed via VC, and should delete data as soon as they are no longer needed for verification purposes
  * Verifiers should not expect all elements in the VC to match their own records, but can still use elements conveyed in the VC. For example, if a user has registered a verifier-specific email addresses in the VC, the verifier might use the email address inside the VC as a second factor in a verification workflow

**<ins>VaccineCredentialImmunization</ins>**
* Recommended for inclusion:
  * Vaccine product code and display name
  * Vaccine manufacturer lot number
  * Dose number
  * Series number
  * Date of administration
  * Location of administration
  * Discuss: should this be limited in granularity, e.g., just state or country?
* Recommended for exclusion:
  * Vaccine expiration date
  * Body site of administration
  * Individual who administered vaccine
  * Funding source
  * Reactions

**Comment by jmandel** [comment]
Re: demographics recommended for inclusion in Patient, I want to articulate a few principles that should help us pare down the demographics data set:

* Health Cards are designed to be presented together with (or in the context of) some external understanding of this person's identity (e.g., a physical state ID, or an online traveler account).
* We want to include only enough demographics in the Health Card to facilitate this workflow.
* Supporting something like "patient matching" (where you pass in a Health Card and blast a query against a whole population of patient data to try to identify matches) is explicitly out of scope.
* There's no such thing as perfect; immunizations can't provide perfect protection from disease, and identity binding can't provide perfect assurance of who a person is. Overall we want to achieve a good blend of risks and assurances, without unnecessary spread of PII.

As such, we should be focused on "just enough" data to bind against an existing identity or account, while making sure data are easy to collect (i.e., part of existing immunization workflows). The sweet spot here is probably something as simple as:

* Name
* DOB
* State of residence

This would limit "credential lending" to a very small set of people; there's a threat where people (say) try to sell a copy of their credential to other residents of their own state who share the same name and birth date -- but this is acceptable in the overall context of VCI's work.

**Comment by masnick** [comment]
@jmandel do you think name, DOB, state should should be `1..1` in addition to MS?

**Comment by jmandel** [comment]
Practically, I think we want to establish expectations that these fields (and not others) are the ones that Issuers include. I'm not sure if that means we want to "require" / "prohibit", vs "encourage" / "discourage". We can talk through this in our discussion about how to craft conformance language.

**Comment by rickybloomfield** [comment]
+1 to @jmandel's comments here. In these conversations there's often confusion about the "patient matching" question because the most common traditional matching scenario is one-to-many (e.g., matching a patient to an entire hospital or insurer database). In this case it's a far narrow scope, with matching needing to happen with another single identity. So far less data should be required to achieve a reasonable level of confidence. These changes make sense to me.

**Comment by jmandel** [comment]
Just to call this out explicitly, our recent discussion has focused on name + DOB; we wouldn't expect to see gender included in the data minimization profile. Current [DM profile ](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/StructureDefinition-vaccine-credential-patient-dm.html) are showing gender as must-support:

![image](https://user-images.githubusercontent.com/313089/111218277-85bfc380-85a4-11eb-851d-d1f3be2d30f1.png)

**Comment by masnick** [comment]
I think we made this MS because it's important in IIS, but that was before we had clear criteria for what should be MS. I will remove the MS label, and will also follow up with an IIS expert to make sure I'm not missing anything here.

**Comment by masnick** [comment]
This is why `gender` is MS: https://github.com/dvci/vaccine-credential-ig/pull/31#issuecomment-773434836

While the VCI bundle may be populated from IIS, I can't think of a use case indicating we would *need* to have `gender` in the bundle. I will back out the MS.
