### ISSUE TITLE
Restrict dates to "day" (at least in examples + recommendations)

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#35]
The specific timing (on a given day) of immunizations shouldn't be relevant for demonstration of vaccination status; it adds to payload size and contributes unnecessary information. We should recommend date-level precision and should show dates (no specific time) in our examples. We could capture this suggestion in an information/warning (not error) invariant.

**Comment by masnick** [comment]
I like this approach!
