### ISSUE TITLE
Remove detailed address and contact info from Patient

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#37]
Based on our use cases of matching to existing records (e.g, a driver's license, employer system, travel system, etc) the value of detailed contact information is low. We should:

* Profile `Patient.address` to include country + postal code only
* Remove "must-support" from `Patient.telecom` (thereby discouraging use for phone numbers and email)
* Remove the more detailed demographics from our examples

**Comment by masnick** [comment]
@jmandel are you saying you want `Patient.address.line` and `Patient.address.city` to be `0..0`, or just no longer MS?

And do you think `Patient.address.postalCode` and `Patient.address.country` should be MS?

**Comment by masnick** [comment]
Also, a heads up: there are some conflicts between this issue and #34.

**Comment by jmandel** [comment]
This issue is designed to meet the principle outlined in #34 with more specific guidance (e.g., better aligned with what's on paper vaccination records and omit extraneous data.). The challenge with demographics-based matching is that we never have a "hard line"; more data always allows better (desirable) matching but also undesirable spread of PII.

I think we should list address.line as 0..0 and mark country and postal code as must support.

Beyond that, let's schedule a call to discuss when to use cardinality vs MS vs other guidance to get across our intentions!

**Comment by nkarip** [comment]
Address is set to 0..0 in the recently published data minimization profile, which I think partially addresses this. Do we also want to set restrictions on line, country, postal code on the allowable data profile?

**Comment by masnick** [comment]
@nkarip this is a bug in v0.2.0-dev. The DM profile goes too far by making address `0..0` (which is my fault). I'm going to do a hotfix release.

**Comment by masnick** [comment]
Fixed in `main`. AD has postal code and country as MS, DM has `0..0` for all other Address sub-elements.
