### ISSUE TITLE
Add profiles for COVID-related lab tests

### ISSUE THREAD

**Issue by masnick** [dvci/vaccine-credential-ig#44]
Add profiles to support PCR and serology lab tests. Also consider which other lab tests might be helpful, or leave this open-ended. But we should have examples covering PCR and serology at a minimum based on stakeholder requests.

The current plan is to base our profile on https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-observation-lab.html. If possible we will inherit directly from this profile; if not, we will make sure that resources conforming to our profile will also validate with the US Core profile.

**Comment by masnick** [comment]
### Which LOINC codes should be included?

In the US Core labs profile, `Observation.code` is extensibly bound to all LOINC codes. If we directly follow our approach with a required binding of `Immunization.vaccineCode` to all CVX codes, we would bind `Observation.code` to LOINC with a required rather than extensible binding, and use the "catch code" approach to allow for non-LOINC values. This is what this looks like for `vaccineCode`:

```json
  "vaccineCode": {
    "coding": [
      {
        "system": "http://hl7.org/fhir/us/vaccinecredential/CodeSystem/vaccine-credential-catch-code-cs",
        "code": "OTHER-VACCINE"
      },
      {
        "code": "acme-inc-covid-temporary-code",
        "display": "Acme, Inc. COVID-19 vaccine (EUA)"
      }
    ]
  },
```

The reason we take the required+catch code approach is we want to make sure deviations from the CVX value set are intentional, while still allowing for flexibility in case the value set lags behind the on-the-ground situation.

#### Questions

1. Rather than allowing all LOINC codes, do we want to restrict to just COVID-related LOINC codes, or a subset of these?
2. Do we also want to use the required binding + catch code approach here?

**Comment by nkarip** [comment]
USCoreLaboratoryResultObservationProfile mandates reference to USCorePatient for subject, which we are no longer using for VaccineCredentialPatient. Will need to profile core Observation. Also, USCore requires status and allows dataAbsentReason (If there is no component or related element then either a value[x] or a data absent reason must be present), which we might want to disallow and non-final or non-amended results or results that did not result for whatever reason.
