### ISSUE TITLE
Omit extra data in example bundles?

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#5]
There are some details in the example bundles that come "along for the ride" with the publisher:

```
  "id" : "Scenario1Bundle",
  "meta" : {
    "profile" : [
      "http://hl7.org/fhir/us/vaccinecredential/StructureDefinition/vaccine-credential-bundle"
    ]
  },
```

The `id` doesn't contribute when the bundle is embedded in a VC, and the `profile` is duplicative with 1) VC type and 2) `targetDisease` (if we keep that; see #2). 

Can these be left out? Or if not, can we note that they won't/needn't be present in real data? The issue is that *lots* of real-world data comes from copy/paste of examples :-)

**Comment by masnick** [comment]
Both `id` and `meta.profile` are generated by SUSHI when it processes the FSH representation of the resource instance, so they can't be easily removed. You can see [neither are specified](https://github.com/dvci/vaccine-credential-ig/blob/6145cad81455ac1722a917479581d05efe7ead28/input/fsh/examples_scenario1.fsh#L68-L81) in the FSH. We can add a note explaining this to the example.

For reference for when I write the note, `meta.profile` is supposed to be populated by FHIR producers who publish a CapabilityStatement indicating support for a given profile: https://www.hl7.org/fhir/profiling.html#CapabilityStatement.rest.resource.supportedProfile. But I don't think many/any producers actually do this, and it's not necessary for the resource instance to validate.

**Comment by masnick** [comment]
Covered by #24
