### ISSUE TITLE
Omit "text" / <div> rendering from examples

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#6]
This is related to #4 but text renderings like:

              "div" : "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p><b>Generated Narrative</b></p><p><b>identifier</b>: Medical Record Number: m123 (USUAL)</p><p><b>name</b>: John B. Anyperson </p><p><b>gender</b>: male</p><p><b>birthDate</b>: 1951-01-20</p><p><b>address</b>: 123 Main St Anytown 12345 US </p><h3>Contacts</h3><table class=\"grid\"><tr><td>-</td><td><b>Telecom</b></td></tr><tr><td>*</td><td>ph: 555-555-5555(HOME), <a href=\"mailto:john.anyperson@example.com\">john.anyperson@example.com</a></td></tr></table><h3>Communications</h3><table class=\"grid\"><tr><td>-</td><td><b>Language</b></td></tr><tr><td>*</td><td><span title=\"Codes: {urn:ietf:bcp:47 en-US}\">English</span></td></tr></table></div>"

are 1) large, 2) redundant, and 3) hard to selectively redact. Is there an important reason to include them in a Health Card?

**Comment by masnick** [comment]
This is another field generated by SUSHI parsing the FSH.

**Comment by masnick** [comment]
Covered by #24
