### ISSUE TITLE
References in example bundles are broken

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#60]
http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/Bundle-Scenario1Bundle.json has

```
      "fullUrl": "resource:0",
      "resource": {
        "resourceType": "Patient",
```

and

```
      "fullUrl": "resource:1",
      "resource": {
        "resourceType": "Immunization",
        "patient": {
          "reference": "Patient/Scenario1Patient"
        },
```

The 2nd reference should say `resource:0` instead of `Patient/Scenario1Patient`. (I'm not sure why the build tooling doesn't choke on this bundle; it seems to have invalid references. But maybe it assumes they're valid references to something external?)

**Comment by isaacvetter** [comment]
Hey Friends, I wonder if this is just a matter of getting everyone on the same page. 

>the 2nd reference should say `resource:0` instead of `Patient/Scenario1Patient`.

 I **think** that this change is inconsistent with the intent (only currently described in "prose") of the [dvci IG](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/#data-minimization), according to which the 2nd reference should say `Patient/r:0` instead of `Patient/Scenario1Patient`.

Perhaps the "resource index" is specific to a type of resource, such that the resource type is a necessary prefix? I'd suggest that there's no need and Josh, your approach is minimal and viable.

**Comment by jmandel** [comment]
`Patient/r:0` is not a valid FHIR reference. When referencing via fullUrl, there is no prefix -- just a `{"reference": "<<fullUrl>>"}`

**Comment by jmandel** [comment]
The source of the content in the DVCI bullet list was https://smarthealth.cards/#health-cards-are-small -- I'm not sure where the differences crept in.

**Comment by nkarip** [comment]
I think we fixed these internal references at some point but it got lost in merging madness. Will re-apply those changes. To clarify - fullUrl format "resource:0", actual resource should not have id, and references to resource in format {"reference": "resource:0"} with expectation that they are resolvable within bundle only.

**Comment by nkarip** [comment]
I modified the bundles as above but am unable to remove the id from the individual resource examples due to IG tooling limitations (it fails unless each resource has an id). @masnick I wonder if we should leave out the examples of individual resources, since there isn't a use case in the IG where a card would provide a resource outside of a bundle and there is no way to make the bundle resource instance match exactly to the single resource example?

**Comment by masnick** [comment]
The Bundle examples in `dev` are now using the `resource:0` syntax. References must be like `Patient/resource:0` or they fail validation.

The resource-specific examples unfortunately have to use ids like `"id": "Scenario1Patient"`. I don't want to get rid of those examples as I think it makes understanding the IG more difficult, but I will add a note explaining why these do not use the recommended format.

**Comment by nkarip** [comment]
I looked at the validator source and there is logic around both matching fullUrl to resource id and around bundle reference resolution that makes using the combination of resource:x format for fullUrl and reference with no resource id throw an error. The only way it seems it will validate is using urn:uuid for fullUrl and references, which I think @jmandel wanted to avoid due to length. It does not seem to require a GUID for uuid though, I was able to use urn:uuid:0 without validation errors in the linked PR.

**Comment by jmandel** [comment]
Re: `urn:uuid:0` -- I'm not a huge fan just for the reason that this isn't actually a valid uuid, and I don't love the idea designing APIs / constraints around current validator quirks.

https://jira.hl7.org/browse/FHIR-31422 is currently open to track this in FHIR Core.

**Comment by masnick** [comment]
@jmandel @nkarip so it sounds like the ideal solution (ignoring the FHIR Validator) is:

1. Setting `"fullUrl": "resource:n"` on each entry in the Bundle, where `n` is a unique whole number within the Bundle.
2. **Not** setting `id` on any entry within the Bundle.
3. Using `"reference": "resource:n"` within the Bundle where references are needed (as opposed to `Patient/resource:n`).

Did I get this right?

If this is what we want, do we want to raise on Zulip or get on the FHIR-I agenda for next week to see if we can get the validator updated to support this?

I would really like to avoid having to tell implementers to ignore specific validation errors/warnings -- it's confusing and will lead to people inadvertently ignoring legitimate issues.

And should we go as far as cutting a pull request against the FHIR validator to support this? Sounds like @nkarip already found the relevant code and I doubt this is a technically difficult change.

**Comment by masnick** [comment]
As Josh notes in #81:

> `Patient/resource:0` is actually not a valid Bundle-internal reference; the FHIR validator may have a non-standard behavior that allows it, but this has been reviewed is _not_ valid behavior (see the resolution on https://jira.hl7.org/browse/FHIR-29271).

**Comment by jmandel** [comment]
On the decision side: We can ask FHIR infrastructure to put this item on the agenda for next week, to make sure we get an answer quickly.

And sure on the release side: I bet if we can submit a PR to the validator that would help move things along on the release side.

**Comment by jmandel** [comment]
(I put in a request status to the FHIR-I note this will be almost two weeks from now because the call next week is canceled for the ONC annual meeting.)

**Comment by nkarip** [comment]
Are we anticipating any pushback on this? We can submit a PR but might be helpful to bring it up on Zulip first, since the core Bundle does specify UUID. Would it be open to any old scheme or a restricted set?

**Comment by jmandel** [comment]
I'm not sure what to expect -- haven't seen feedback on this yet. I'd be open to any URI scheme that allows arbitrarily short identifiers (e.g. if we wanted to say "any scheme" or "just `resource:`" or "just `r:`" those would all be fine by me, but my preference would be for FHIR to specify "any scheme".)

**Comment by masnick** [comment]
@jmandel seems like the discussion on https://jira.hl7.org/browse/FHIR-31422 is pointing away from `resource:` as an option at least in the short term.

Trying to think outside the box, could we use something like `urn:uuid:00000000-0000-0000-0000-000000000001`? This is a few bytes bigger than `resource:0` after DEFLATE (if you trust the random online tool I used).

**Comment by jmandel** [comment]
This is fun. I do like your outside-of-the-box thought (as much as it makes me cringe). Will play with this a bit in the example generator...

**Comment by jmandel** [comment]
In before/after comparison for our 3 example bundles, the byte counts increase as follows:

* 834->854 for `docs/examples/example-00-d-jws.txt`
* 834->860 for `docs/examples/example-01-d-jws.txt`
* 3309->3378 for `docs/examples/example-02-d-jws.txt`

**Comment by jmandel** [comment]
Using a prefix like `https://smarthealth.cards/resource/` saves a bit of space (post-DEFLATE) over 0-padded UUIDs, but I don't like the potential for confusion about what's dereferenceable on the web.

**Comment by masnick** [comment]
Hah, I went as far as looking at availability of super short domain names before reaching that same conclusion about potential confusion.

So the gross UUID 0 padding may be our best option if we want to produce letter-of-the-law valid FHIR Bundles. I worry that if we deviate from this, we will end up having to change it later as part of HL7 balloting, which will be at best annoying to implementers.

I would also like to have clean validation now if possible, which the UUID thing gets us.

We could also continue to take advantage of the FHIR validator not checking the UUID format and using `urn:uuid:0`.

@jmandel and @nkarip, what do you think? Once we're in agreement on an approach, we could run it by FHIR-I as well.

**Comment by nkarip** [comment]
Changing to a short URL like https://smarthealth.cards/resource/1 causes a "Resource requires an id, but none is present" error in the validator - there is some logic in there that checks that the id portion of a url matches the resource id in certain cases.

**Comment by masnick** [comment]
Oh good point, so if we use `http://whatever/1` we will have to add back in `"id": "1"`?

If so that probably means we are stuck with `urn:` which for now is restricted to `urn:uuid`.

**Comment by jmandel** [comment]
Vassil's comment also mentions `urn:oid` -- does the validator support this too? (Not that I want to go there, just trying to understand current gaps between spec + validator.)

**Comment by jmandel** [comment]
> FHIR validator not checking the UUID format and using urn:uuid:0.

If the goal is validator compatibility... this would make us very unhappy on some unpredictable future date when someone "improves" the validator :-)

**Comment by masnick** [comment]
@nkarip do you have a link to the code in the validator that you looked at for this?

**Comment by jmandel** [comment]
To be clear, my first choice is still to see if we can get a resolution on FHIR-31422; the prospect of using "UUIDs" that aren't in fact *Universally Unique* seems like it does not meet the "letter-of-the-law" goals, even if it does satisfy the FHIR validator.

**Comment by jmandel** [comment]
If there's no sensible resolution to this, we can just say:

> For purposes of sizes reduction, the `fhirBundle` claim packaged into a SMART Health Card is actually a precursor to a FHIR bundle; to turn it into a proper FHIR Bundle for validation with standardized tooling, you should first remap each `resource:x` reference to a uuid.v4(), and then proceed.

**Comment by masnick** [comment]
That may be what we want to do. The zero-padded UUID is more confusing than what you said above IMO.

**Comment by jmandel** [comment]
From vassil's `urn:oid:2.16.840.1.113883.20.` +"x"  suggestion:

In before/after comparison for our 3 example bundles, the byte counts increase as follows:

* 836->864 for `docs/examples/example-00-d-jws.txt`
* 842->869 for `docs/examples/example-01-d-jws.txt`
* 3312->3341 for `docs/examples/example-02-d-jws.txt`

Advantages:
* (? need to confirm) validator deals happily with files like [this one](https://gist.github.com/jmandel/7f300edf3d555364017174492711c537)
Disadvantages:
* OIDs are opaque and confusing for implementers and I thought I'd left them behind
* Developers are likely to mess this up (can be mitigated with good validation testing + warnings)
* Breaking change to our representation of health cards

**Comment by nkarip** [comment]
Confirmed that using urn:oid:2.16.840.1.113883.20. +"x" in bundles does not cause errors in the validator.

Going back to @masnick's suggestion to use https://smarthealth.cards/resource/1 - this fails in validation due to "Resource requires an id, but none is present" error, but based on my reading of http://build.fhir.org/bundle-definitions.html#Bundle.entry.fullUrl it seems like the validator is mis-interpreting the requirement. It is requiring a Resource.id whenever fullUrl is not a urn, but it seems like it should only do so when fullUrl matches the RESTful regex, which https://smarthealth.cards/resource/ does not. 

Can we float this by the FHIR core folks? If this is the correct interpretation, then using https://smarthealth.cards/resource/x seems less opaque than oid. The validator would need a minor fix.

**Comment by jmandel** [comment]
> confusion about what is dereferenceable but I think it can be specified in documentation

My worry is that software processing these bundles might include things like automatic fetch of referenced URIs, and our English language documentation will be opaque to these kinds of tools.

**Comment by masnick** [comment]
@nkarip I believe we are going to bring this to the FHIR-I call next Monday. This week is canceled.

I don't see a place on Confluence with an agenda yet. [This is last week](https://confluence.hl7.org/display/FHIRI/FHIR+Infrastructure+Minutes+CC+20210322).

@jmandel do we need to do anything else to get on the agenda, and do you want one of us to lead the discussion from our side next week? I'm happy to do it if @nkarip can't.

**Comment by jmandel** [comment]
I'm planning to join the call; it'd be great if someone from the MITRE team (and other interested parties) could join too, for discussion / vote. (This could be contentious givemn discussion so far.)

I've asked on Zulip on #fhir/infrastructure-wg to include this issue on our agenda for next week.

**Comment by masnick** [comment]
I will plan to attend. Thanks, Josh!
