### ISSUE TITLE
might lab result time actually be important?

### ISSUE THREAD

**Issue by isaacvetter** [dvci/vaccine-credential-ig#61]
[Data minimization guidance](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/#data-minimization) says this:
>Use YYYY-MM-DD precision for all dateTime fields. Greater precision will result in a warning when validating a resource.

Here are the datetime fields in the profiles:
* Immunization.occurrenceDateTime
* Observation.effectiveDateTime

Given that verifier business logic often counts the validity of lab results in hours, it seems like a mistake to not include the time at which a lab result occurred. Optimally, hours and maybe minutes would be included.

Re-reading the [FHIR DateTime data type definition](http://hl7.org/fhir/R4/datatypes.html#dateTime) I see that if we include hours, we're also stuck include minutes, seconds and timezone. So, it's an additional 15 characters. If you agree with my logic above, maybe we should just add time to Observation?

**Comment by nkarip** [comment]
For Immunization.occurrenceDateTime, there isn't a clinical scenario I can think of that would require specific time of an immunization. They don't typically include time when reported to a registry and none of the existing CDC guidance around vaccine forecasting breaks intervals down to hours or minutes. 

For Observation though, I think you might have a point. I don't think we can just add time to the Observation - if someone has business logic so specific as to specify time intervals down to hours, then timezone could be a factor. Flying from CA to MA crosses time zones, and if you need a negative test within the last 24 hours to enter the state then timezone makes a difference.

**Comment by nkarip** [comment]
Fixed in dev branch - adjusted language in Data minimization section, date-invariant warning only applies to Immunizations (not applied to lab profiles).
