### ISSUE TITLE
MustSupport review

### ISSUE THREAD

**Issue by isaacvetter** [dvci/vaccine-credential-ig#62]
These are more questions than specific feedback:
* [x] [Immunization.patient](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/StructureDefinition-vaccine-credential-immunization-dm.html) is currently 1..1, but not MustSupport? It should be MS, right?
*  [x] Immunization.status is 1..1 in the [base resource](https://www.hl7.org/fhir/immunization.html), but not MustSupport [in the minimization profile](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/StructureDefinition-vaccine-credential-immunization-dm.html). Does this mean that implementers should include it? What if it's always `complete`?
*  [x] [Patient.Address isn't MustSupport](http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/main/StructureDefinition-vaccine-credential-patient-dm.html), but Patient.Adress.country and .zip are. Is this intentional?
*  [x] As noted in the comments on #59, Bundle.type should be MustSupport.

**Comment by isaacvetter** [comment]
#70 is also asking about Immunization.status

**Comment by masnick** [comment]
> Immunization.patient is currently 1..1, but not MustSupport? It should be MS, right?
Fixed in `dev`

**Comment by masnick** [comment]
> Immunization.status is 1..1 in the base resource, but not MustSupport in the minimization profile. Does this mean that implementers should include it? What if it's always complete?

We don't have a choice about this since it's inherited as `1..1` from the base resource -- it has to be included even though it's always `complete`. I have changed it to `MS` in the AD profile for consistency in `dev`.

**Comment by masnick** [comment]
>  Patient.Address isn't MustSupport, but Patient.Adress.country and .zip are. Is this intentional?

This is a bug -- `address` is now MS in `dev`.

**Comment by masnick** [comment]
> Bundle.type should be MustSupport.

Fixed in `dev`

**Comment by masnick** [comment]
All the issues listed here are fixed in the `dev` branch. Thank you for the help finding these issues!!
