### ISSUE TITLE
Consider adding name.text as must support

### ISSUE THREAD

**Issue by yunwwang** [dvci/vaccine-credential-ig#65]
Some countries, esp in East Asia, use single field for patient's name. This was discussed in the early stage of FHIR and FHIR-I recommended using name.text for that purpose. If this IG is intended to be used internationally, I suggest to mark name.text as must support and add clarification that one of the name.text, name.family, and name.given must be supported.

**Comment by nkarip** [comment]
This is accomplished via the invariant 'name-invariant'. We do not want to make name.text MS in addition to family and given because family and given are preferred, and if they are available then text should not be included. The invariant checks for text in cases where family/given are not present.

**Comment by yunwwang** [comment]
"family and given are preferred" This is true in US. That's why I added a condition: "If this IG is intended to be used internationally"

**Comment by jmandel** [comment]
I think we've been looking at this IG as US specific; it builds on US Core designs (where appropriate).
