### ISSUE TITLE
Provide strict guidance for Patient.identifier

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#7]
Examples follow US Core Patient with identifiers like:

```
 "identifier" : [
          {
            "use" : "usual",
            "type" : {
              "coding" : [
                {
                  "system" : "http://terminology.hl7.org/CodeSystem/v2-0203",
                  "code" : "MR",
                  "display" : "Medical Record Number"
                }
              ]
            },
            "system" : "http://hospital.example.org",
            "value" : "m123"
          }
        ]
```

... but this is unsuitable for Health Cards, where we want to minimize data and where organization-specific identifiers are unlikely to be more broadly interpretable. We should omit identifiers in examples, and our guidance should be to omit identifiers.

**Comment by masnick** [comment]
Very good point.

Unfortunately https://www.hl7.org/fhir/us/core/StructureDefinition-us-core-patient.html sets the identifier cardinality to `1..*` so we can't zero it out unless we use `Patient` instead of `USCorePatientProfile`.

**Comment by jmandel** [comment]
Yep. I guess this means we'll want to build a "US Patient Inspired for Health Cards" profile. This is probably good anyway, because US Core also has things like must-support for fields like Patient race, ethnicity, communication language, and birth sex, which we wouldn't intend to include in health cards, from a data minimization perspective.

**Comment by masnick** [comment]
Ok I'm going to close this and open a new issue to profile Patient directly. Thanks!
