### ISSUE TITLE
Do we need a data minimization version of the Bundle profile?

### ISSUE THREAD

**Issue by masnick** [dvci/vaccine-credential-ig#75]

**Comment by jmandel** [comment]
Without this, it's hard to apply the validator to a Health Card's contents

**Comment by masnick** [comment]
Added in `dev` in 4f2e2c7ecbcfc0a04a760acef4d4b5f1c6d9ae3d.

For the lab results, there are two different DM bundles. This is due to how we're handling COVID lab tests vs. generic lab tests -- for the AD bundle we use an abstract parent profile, but this probably does not give you the specificity you want for testing.

The issue is that the publisher can't distinguish between the COVID and generic lab results profiles -- and there's no good way I can think of to fix this without making a change that we wouldn't want (like making a required value set of non-COVID LOINC for the generic lab results).

Please open another issue if it's helpful to have separate AD bundles for COVID and generic lab results.
