### ISSUE TITLE
IAL produces validation warning

### ISSUE THREAD

**Issue by masnick** [dvci/vaccine-credential-ig#79]
```
  "meta": {
    "security": [{"code": "IAL1"}]
  },
```
produces a validation warning:

> Warning @ Immunization.meta.security[0] (line 5, col19) : A code with no system has no defined meaning. A system should be provided

@nkarip @jmandel I assume we don't want to add a system to this for data minimization reasons. Ideally the validation would not have any warnings to make it easier for implementers to determine if they have valid resources. Before I create a "list of warnings you can ignore," are we sure we don't want a system in this?

**Comment by jmandel** [comment]
In principle I'd rather not have FHIR validator default behaviors driving out design. it would be nicer if you could pass in a list of flags to the validator telling it what kinds of errors or specific paths to ignore, the same way you would for a linter.

If we *do* add a system, I'd prefer it to be `https://smarthealth.cards`;  I'm not sure if that would also cause problems with the validator or publication tooling?

**Comment by masnick** [comment]
> In principle I'd rather not have FHIR validator default behaviors driving out design.

I agree

>  it would be nicer if you could pass in a list of flags to the validator telling it what kinds of errors or specific paths to ignore, the same way you would for a linter.

Also agree, but I don't see anything indicating this is possible in the docs: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator

For now I will just list "warnings to ignore" in the IG. We can look for a more robust solution later.

**Comment by masnick** [comment]
Added to angry red box on index.html in `dev`
