### ISSUE TITLE
Add support for international code systems for Immunization

### ISSUE THREAD

**Issue by masnick** [dvci/vaccine-credential-ig#83]
This may have some useful information: https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf

**Comment by masnick** [comment]
[Via Zulip](https://chat.fhir.org/#narrow/stream/179202-terminology/topic/COVID-19.20-.20ICD-11.20Vaccine.20Codes.20-/near/231368468):

```
curl -X "POST" "https://terminz.azurewebsites.net/fhir/ValueSet/covid-19-vaccines/$expand" \
     -H 'Accept: application/json' \
     -H 'Content-Type: application/fhir+xml;charset=UTF-8'
```

returns codes from the following systems:

- http://www.whocc.no/atc (version 2022) 
- http://snomed.info/sct (version http://snomed.info/sct/21000210109/version/20210131) 
- http://hl7.org/fhir/sid/cvx (version 14) 
- http://nzmt.org.nz (version 3.6.0.3) 
- http://www.ama-assn.org/go/cpt (version 2021) 
- https://www.humanservices.gov.au/organisations/health-professionals/enablers/air-vaccine-code-formats (version 2021) 
- http://snomed.info/sct/32506021000036107 (version 20210208) 
- http://snomed.info/sct/999000041000000102 (version 20210120)

**Comment by masnick** [comment]
[Via Zulip](https://chat.fhir.org/#narrow/stream/179202-terminology/topic/COVID-19.20-.20ICD-11.20Vaccine.20Codes.20-/near/231456735):

```
WHO ICD-11 (Foundation) - ICD-11 Maintenance Platform
https://icd.who.int/dev11/f/en
Last Update: Mar 22, 2021

COVID-19 vaccine - WHO ICD-11 (Foundation)
https://icd.who.int/dev11/f/en#/http%3a%2f%2fid.who.int%2ficd%2fentity%2f894585096

894585096 COVID-19 vaccine
---- 1104808441 COVID-19 vaccine, inactivated virus
---- 993066376 COVID-19 vaccine, live attenuated virus
---- 264142908 COVID-19 vaccine, non-replicating viral vector
---- 877986394 COVID-19 vaccine, replicating viral vector
---- 1368305645 COVID-19 vaccine, virus protein subunit
---- 729916172 COVID-19 vaccine, virus like particle (VLP)
---- 1316179031 COVID-19 vaccine, DNA based
---- 873941688 COVID-19 vaccine, RNA based

IMPORTANT Note: The content made availabe here is not a released version of the ICD-11. It is a work in progress in between released versions
```

**Comment by p9g** [comment]
https://github.com/who-int/svc/blob/main/input/fsh/svc-valuesets.fsh possibly?

**Comment by masnick** [comment]
http://build.fhir.org/ig/HL7/fhir-ips/ValueSet-vaccines-uv-ips.json

**Comment by masnick** [comment]
PR merged
