### ISSUE TITLE
Questions on data dictionary

### ISSUE THREAD

**Issue by arztnh** [dvci/vaccine-credential-ig#87]
Sorry if these are late...

On the data dictionary spreadsheet, I have a few questions:

1. Some of the profile URLs on the Profiles tab are not valid (http://hl7.org/fhir/us/smarthealthcards-vaccination/StructureDefinition/vaccine-credential-immunization is one)
2. The definition of "Immunization: Occurrence" includes the "date vaccine administered or WAS TO BE administered." What does this "was to be" mean?
3. While I understand that the record is intended to convey clinical knowledge and not an evaluation or application of that knowledge, I see no way in the current data list to determine if a vaccination dose is invalid even though it had been administered (sub-potency is just one reason for a dose being invalid and most source systems would not even capture a dose deemed invalid for this particular reason). A more likely reason for an invalid dose is inappropriate timing with respect to other vaccinations, doses, or the patient's age. Though in some ways still suboptimal, the notion of a declared dose number (which appears to have been lost - or am I just missing it?) is a common surrogate for assuming the issuer is substantiating that at least they believe the dose is valid (but that itself is a value judgement and not a simple assertion of clinical data).

Thanks!

**Comment by nkarip** [comment]
1. Profile URLs will not resolve in the build environment. They are supposed to be stable so we do not want to have a temporary URL in build.
2. This is inherited from the core Immunization and doesn't apply in this context.
3. We removed value judgements - in this context a verifier would need to use a validation or "pass app" to determine whether or not a series was clinically valid. Any value judgments will not be reliably provided and will not eliminate the need for this processing, so they are were omitted.

**Comment by masnick** [comment]
I have fixed (2) in a PR (will show up here when I push the branch). Thanks @arztnh for identifying this inconsistency.
