### ISSUE TITLE
Patient MS data elements - gender, postalCode and country 

### ISSUE THREAD

**Issue by nkarip** [dvci/vaccine-credential-ig#88]
@jmandel brought up issues in a PR that should be discussed - 
1. gender is not MS, should it be disallowed in DM profile?
2. postalCode and country  are currently MS, is there a use case for this?

**Comment by jmandel** [comment]
Thanks @nkarip! My take is:

1. Gender should be disallowed in DM proffile, since it isn't MS (and shouldn't be MS)
2. We have not identified a use case for postalCode and country; we should remove the MS marker from each of these elements if we don't identify a reason to retain the MS designation

**Comment by nkarip** [comment]
Gender I think makes sense. Conversation in this closed issue #37 seems to indicate we thought there was a use case for country and postalCode for demographic based patient matching. It is not included on the paper vaccine card though.

**Comment by jmandel** [comment]
Agreed that in #37 we said "leave postal code" -- though the primary context was "leave out detailed address".

Given discussions over the past 6 weeks, I think less is more (from MS perspective; we can always ramp up in the future). Do we have a use case for country or state, independent of postal code?

**Comment by masnick** [comment]
We initially had gender as MS because we thought it might be important when dealing with IIS. I checked with an IIS SME and this is not the case. As this is the only reason I can recall for gender being MS, I agree MS should be removed from the AD profile and it should be `0..0` in the DM profile.

For `postalCode` and `country`, what you all said up above makes sense to me. These would also lose MS in AD and gain `0..0` in DM.

This is a breaking change for the DM profiles because it will invalidate previously valid resources, so we will want to clearly communicate this in the changelog.

**Comment by masnick** [comment]
Fixed in `dev`

**Comment by arztnh** [comment]
Many (most?) IIS reject a query if gender is not present (though an
    "unknown" code is often acceptable). But if you are talking about
    what is presented in the credential you can show as much or
    as little as you want. But recognize that gender is useful often as
    a way to help visibly corroborate the identity of record holder: if
    I see a gender in the credential I can look at the
    person in front of me...
    
    Noam
    
    On 4/6/2021 5:46 AM, Max Masnick wrote:
    
    
      
      We initially had gender as MS because we thought it might be
        important when dealing with IIS. I checked with an IIS SME and
        this is not the case. As this is the only reason I can recall
        for gender being MS, I agree MS should be removed from the AD
        profile and it should be 0..0 in the DM profile.
      For postalCode and country, what
        you all said up above makes sense to me. These would also lose
        MS in AD and gain 0..0 in DM.
      This is a breaking change for the DM profiles because it will
        invalidate previously valid resources, so we will want to
        clearly communicate this in the changelog.
      —
        You are receiving this because you are subscribed to this
        thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/dvci/vaccine-credential-ig/issues/88#issuecomment-814091205",
"url": "https://github.com/dvci/vaccine-credential-ig/issues/88#issuecomment-814091205",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by masnick** [comment]
@arztnh:

> But recognize that gender is useful often as a way to help visibly corroborate the identity of record holder: if I see a gender in the credential I can look at the person in front of me...

One of our [key design principles](https://vci.org/about) is "flexible and equitable". Trying to visually match someone's self-identified gender to their physical appearance could result in an inequitable verification process.

It's also possible that someone's self-identified gender could change over time, but it may not be possible to re-issue the credential to update this.
