### ISSUE TITLE
Do not "leak" server information in fullUrls / references

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#9]
We want to avoid conveying full server URL details in a Health Card.

~~Our current approach is to use FHIR bundle reference resolution semantics by assigning a UUID to every resource and linking based on those. https://github.com/microsoft-healthcare-madison/health-wallet-demo/blob/master/src/fixtures/vc.json has an example.~~

Our [updated approach](https://github.com/smart-on-fhir/health-cards/blob/0c7813c95c1cac0704ca3c3978aa76bc5e763e2c/docs/index.md) is to use FHIR bundle reference resolution semantics by assigning a `resource:` value:

*  `Bundle.entry.fullUrl` populated with short resource-scheme URIs
   * e.g., in `Bundle.entry`, you'd see `{"fullUrl": "resource:0"}`
*  `Reference.value`  populated with short resource-scheme URIs
   * e.g., in `Immunization`, you'd see `{"patient": {"value": "resource:0"}}`

**Comment by nkarip** [comment]
The core Bundle.entry.fullUrl description and comments have a number of expected conditions. If we want to further restrict without violating the original constraints, we could change to the following. @masnick what do you think?

> The fullUrl SHALL be a urn:uuid or an absolute URL that does not end with the logical id of the resource (Resource.id) and does not look like a RESTful server URL.

For references, I think we might have to go through and modify description to each instance in the profiles to indicate something similar, unless there is a simpler way to document this.

**Comment by jmandel** [comment]
Oh, and I've updated guidance since creating this issue -- I just updated the original comment above to clarify. Basically

1. The use case doesn't require a UUID, since references only need to be resolved within a bundle and *shouldn't* be correlated or used outside the bundle 
2. UUIDs add 128 bits of entropy to the payload (each), and we want to keep payloads small


--> short local URIs like `resource:0` help here.

**Comment by nkarip** [comment]
From a practical perspective, should these criteria go into the IG profiles ie a FHIR server will need to conform to these, or are these modifications something we expect the Issuer/SMART health card participant to modify before producing the payload? I would think the latter, since splitting a bundle and such seems out of scope for what we would expect a FHIR server to handle.

**Comment by jmandel** [comment]
> should these criteria go into the IG profiles ie a FHIR server will need to conform to these,

Hmm, this illustrates maybe we don't have a shared understanding about the scope of this IG.  My understanding is that the goal of this IG is to constrain resources for use in SMART Health Cards. This would apply to Health Cards printed in a QR for a post-visit summary, or to Health Cards offered for download via patient portal, or for Health Cards offered via `/Patient/:id/$HealthWallet.issueVc`.  But it *wouldn't* apply to the FHIR server's REST endpoints; i.e., I'd expect to get *fuller/richer* details if I query "GET /Patient/123/Immunization" from a FHIR server (I should get the US Core info here, at least).

**Comment by masnick** [comment]
> Hmm, this illustrates maybe we don't have a shared understanding about the scope of this IG. My understanding is that the goal of this IG is to constrain resources for use in SMART Health Cards. This would apply to Health Cards printed in a QR for a post-visit summary, or to Health Cards offered for download via patient portal, or for Health Cards offered via /Patient/:id/$HealthWallet.issueVc. But it wouldn't apply to the FHIR server's REST endpoints; i.e., I'd expect to get fuller/richer details if I query GET /Patient/:id/Immunization from a FHIR server (I should get the US Core info here, at least).

I updated the language on `index.md` to reflect this. Thanks!

**Comment by nkarip** [comment]
To follow up - it sounds like we still need language in the IG then regarding fullUrls and resource references, in addition to the guidance provided by the SMART Health Cards spec under https://github.com/smart-on-fhir/health-cards/blob/main/docs/index.md#health-cards-are-small. Is that the case? Or just link to the spec section as additional guidelines?

**Comment by jmandel** [comment]
Re: specific conventions, it'd be good to at least 1) link to the relevant section of the spec, and 2) ensure examples to match (or if they don't, provide some inline warning about this fact).

**Comment by masnick** [comment]
I think this part specifically should be duplicated in the IG to make sure it's not missed:

> without Resource.id elements
> without Resource.meta elements
> without Resource.text elements
> without CodeableConcept.text elements
> without Coding.display elements
> with Bundle.entry.fullUrl populated with short resource-scheme URIs (e.g., {"fullUrl": "resource:0})
> with Reference.reference populated with short resource-scheme URIs (e.g., {"patient": {"reference": "resource:0"}})
