### ISSUE TITLE
Replace default text on Patient.id, Immunization.id, etc

### ISSUE THREAD

**Issue by jmandel** [dvci/vaccine-credential-ig#92]
Discussion from https://github.com/microsoft/health-cards-validation-SDK/issues/34 raised this point

http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/dm-profiles/StructureDefinition-vaccine-credential-patient-dm-definitions.html#Patient.id
and other definitions show ID as 0..1 with a default comment of:

> The only time that a resource does not have an id is when it is being submitted to the server using a create operation.

... but http://build.fhir.org/ig/dvci/vaccine-credential-ig/branches/dm-profiles/index.html#data-minimization provides guidance that `.id` "SHOULD NOT" be populated; so in all data profiles it'd be good to updated the description for `.id` so we're not pulling in this "only time..." guidance from the FHIR base spec, which is inaccurate here.

**Comment by dleve123** [comment]
Would it be approach to just remove `id` from the PatientDM profile? What's a use-case to include it within a SHC?

**Comment by jmandel** [comment]
Good point: for the DM profiles it'd be preferable to remove `id` if the tooling allows (though I suspect there may be some issues there). For the regular profiles, I think the best we can do would be to update the text.

**Comment by nkarip** [comment]
As far as tooling, looks like the IG tooling allows setting id to 0..0 in profiles but fails when resource examples do not have an id. FHIR validator allows it though.

**Comment by masnick** [comment]
Fixed in a forthcoming PR.
